### ISSUE TITLE
Python tests failed on : ImportError: cannot import name 'epylint' from 'pylint' 

### ISSUE THREAD

**Issue by NvTimLiu** [NVIDIA/spark-rapids-ml#458] opened 2023-10-04 11:10 UTC
Python tests failed on : ImportError: cannot import name 'epylint' from 'pylint'  for 23.10.0-SNAPSHOT

Nightly build job: spark-rapids-ml_nightly/176

```
+ bash ci/test.sh nightly
......

 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
 + ./run_test.sh --runslow
 Traceback (most recent call last):
   File "/home/jenkins/agent/workspace/jenkins-spark-rapids-ml_nightly-176/python/../ci/lint_python.py", line 8, in <module>
     from pylint import epylint
 ImportError: cannot import name 'epylint' from 'pylint' (/root/miniconda3/lib/python3.9/site-packages/pylint/__init__.py)
script returned exit code 1
```

**Comment by lijinf2** [comment] 2023-10-04 17:34
Thanks for reporting this issue! 

PR https://github.com/NVIDIA/spark-rapids-ml/pull/457 was submitted to fix the issue and just got merged.

**Comment by pxLi** [comment] 2023-10-05 05:58
confirmed the issue is resolved

**Closed by pxLi** 2023-10-05 05:58 UTC
